---

- name: check volume_path
  stat:
    path: "{{ volume_path }}"
  register: vp

- debug:
    msg: "{{ vp }}"

- name: fdisk output alma
  shell: fdisk -l "{{ volume_path }}"
  register: fp
  when: vp.stat.isblk is defined and vp.stat.isblk

- name: shell output
  debug:
    msg: "{{ fp.stdout_lines }}"
  when: vp.stat.isblk is defined and vp.stat.isblk

- name: ansible path control
  stat:
    path: "{{ file_path_an }}"
  register: asd

- debug:
    msg: "{{ asd }}"

- name: ansible version cekme
  shell: " ansible --version "
  register: av
  when: asd.stat.exists is defined and asd.stat.exists

- debug:
    msg: "{{ av.stdout_lines }}"
  
  
  

  
  
  
#- name: filesystem
#  filesystem:
#    fstype: xfs
#    dev: "{{ volume_path }}1"
#  when: vp.stat.isblk is defined and vp.stat.isblk

#- name: check file_path 
#  stat:
#    path: "{{ file_path }}"
#  register: vp

#- name : cat "{{ file_path }}"
#  shell: 'cat "{{ file_path }}"'
#  register: fp
#  when: vp.stat.pw_name is defined and vp.stat.pw_name

#- name: output command
#  debug:
#    msg: "{{ fp.stdout_lines }}"


